default: &default
  adapter: postgresql
  encoding: unicode
  username: "niteshkumar"
  password: "nitesh"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: studio_development

test:
  <<: *default
  database: studio_test

production:
  <<: *default
  database: studio_production